Update UnitOfWork to be PHP 7.3 compatible
Fix issue on PHP 7.3 where this error is triggered.
Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2636

Doctrine/orm 2.5 is the latest version usable on Symfony 2.8 and must be compatible with PHP 7.3
Solves update conflict for Symfony 2.x projects with PHP 7.3+